spring:
  consul:
    discovery:
      instance-id: ${spring.application.name}:${server.port}
      prefer-ip-address: true
    host: localhost
    port: 8500
  cloud:
    loadbalancer:
      enabled: true
    gateway:
      routes:
        - id: security
          uri: lb://security-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        # 代理微服务，如果同时存在两个服务提供者，但是有一个挂了，则服务轮询机制导致一次好一次坏
        - id: coffee
          uri: lb://server-producer
          predicates:
            - Path=/p/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: info