spring:
  cloud:
    loadbalancer:
      enabled: true
    gateway:
      routes:
        - id: security
          uri: lb://security-server/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: info